# 乐透系统配置文件

# 乐透所选用货币的物品id (请使用标准Minecraft ID)
currency-item: "minecraft:diamond"

# 每名玩家参与乐透需要上交的货币数量
cost-amount: 5

# 每次乐透开始后奖池内初始的货币数量 (系统送的)
initial-pot: 10

# 开始乐透需要的服务器内最小玩家数，设置成 0 代表无限制
min-players: 2

# 每轮乐透从开始到结算的间隔时间，单位秒 (比如开奖持续300秒)
duration-seconds: 300

# 每轮乐透之间的间隔时间，单位秒 (比如上一轮结束后休息600秒再开始下一轮)
interval-seconds: 600

# 乐透结束前需要播报公屏全局消息的时间节点 (剩余多少秒时播报)
broadcast-times:
  - 120
  - 60
  - 30
  - 10
  - 5
  - 3
  - 2
  - 1